[package]
name = "scrobbled"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
axum = "0.8.4"
md5 = "0.8.0"
open = "5.3.2"
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["net", "signal"] }
